# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteFamiliar',
            fields=[
                ('idAntecedenteFamiliar', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('parentesco', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Archivero',
            fields=[
                ('idArchivero', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoAlergia',
            fields=[
                ('idCatalogoAlergia', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=20)),
                ('reaccion', models.CharField(max_length=20)),
                ('tratamiento', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoDepartamento',
            fields=[
                ('idCatalogoDepartamento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreDepartamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoEnfermedad',
            fields=[
                ('idCatalogoEnfermedad', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreEnfermedad', models.CharField(max_length=20)),
                ('descripcionEnfermedad', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoMedicamento',
            fields=[
                ('idCatalogoMedicamento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreMedicamento', models.CharField(max_length=50)),
                ('modoUso', models.TextField(max_length=100)),
                ('efectosSecundarios', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoMunicipio',
            fields=[
                ('idCatalogoMunicipio', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreMunicipio', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.CatalogoDepartamento')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoTipoExamen',
            fields=[
                ('idCatalogoTipoExamen', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreExamen', models.CharField(max_length=20)),
                ('descripcionExamen', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ConstanciaMedica',
            fields=[
                ('idConstanciaMedica', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dirigidaA', models.CharField(max_length=100)),
                ('motivoConstancia', models.TextField()),
                ('fechaEmisionConstancia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idConsulta', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('motivo', models.TextField(max_length=100)),
                ('sintomatologia', models.TextField(max_length=200)),
                ('observaciones', models.TextField(max_length=200)),
                ('diagnostico', models.TextField(max_length=200)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.CatalogoEnfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('detalleDireccion', models.TextField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.CatalogoDepartamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.CatalogoMunicipio')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fechaIngreso', models.DateField()),
                ('tiempoServicio', models.IntegerField()),
                ('jVPM', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadEmpleado',
            fields=[
                ('idEspecialidadEmpleado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipoEspecialidad', models.CharField(max_length=50)),
                ('descripcionEspecialidad', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('idExpediente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fechaElaboracion', models.DateField()),
                ('numeroArchivo', models.CharField(max_length=20)),
                ('alergia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.CatalogoAlergia')),
                ('archivero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Archivero')),
            ],
        ),
        migrations.CreateModel(
            name='IncapacidadMedica',
            fields=[
                ('idIncapacidadMedica', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreEmpresa', models.CharField(max_length=50)),
                ('tipoRiesgo', models.CharField(choices=[('Enfermedad comun', 'Enfermedad comun'), ('Accidente', 'Accidente'), ('Maternidad', 'Maternidad')], max_length=20)),
                ('tipoIncapacidad', models.CharField(choices=[('Inicial', 'Inicial'), ('Prorroga', 'Prorroga')], max_length=50)),
                ('motivoIncapacidad', models.TextField()),
                ('diasIncapacidad', models.IntegerField()),
                ('fechaInicioIncapacidad', models.DateField()),
                ('fechaFinIncapacidad', models.DateField()),
                ('fechaEmisionIncapacidad', models.DateField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Consulta')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenExamenMedico',
            fields=[
                ('idOrdenExamenMedico', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fechaSolicitudExamen', models.DateField()),
                ('estadoOrden', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesando', 'Procesando'), ('Finalizado', 'Finalizado')], max_length=10)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Consulta')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.CatalogoTipoExamen')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipoSangre', models.CharField(choices=[('A+', 'Tipo A+'), ('B+', 'Tipo B+'), ('AB+', 'Tipo AB+'), ('O+', 'Tipo O+'), ('A-', 'Tipo A-'), ('B-', 'Tipo B-'), ('AB-', 'Tipo AB-'), ('O-', 'Tipo O-')], max_length=3)),
                ('fechaNacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('estadoCivil', models.CharField(choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('V', 'Divorciado/a')], max_length=2)),
                ('ocupacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('primerNombre', models.CharField(max_length=20)),
                ('segundoNombre', models.CharField(max_length=20)),
                ('tercerNombre', models.CharField(max_length=20)),
                ('primerApellido', models.CharField(max_length=20)),
                ('segundoApellido', models.CharField(max_length=20)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('dui', models.CharField(max_length=10)),
                ('telefonoFijo', models.CharField(max_length=15)),
                ('telefonoMovil', models.CharField(max_length=15)),
                ('correoElectronico', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('idRecetaMedica', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fechaEmisionReceta', models.DateField()),
                ('observacionesReceta', models.TextField(max_length=100)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Consulta')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaMedicamento',
            fields=[
                ('idRecetaMedicamento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dosis', models.TextField(max_length=100)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.CatalogoMedicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.RecetaMedica')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaMedica',
            fields=[
                ('idReferenciaMedica', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('servicioSolicitado', models.CharField(max_length=20)),
                ('institucionRemitida', models.CharField(max_length=50)),
                ('hallazgosMedicos', models.TextField()),
                ('impresionDiagnostica', models.TextField()),
                ('motivoReferencia', models.TextField()),
                ('fechaEmisionRef', models.DateField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Consulta')),
                ('doctorRemitido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('idResultadoExamen', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fechaResultado', models.DateField()),
                ('descripcionResultado', models.TextField(max_length=100)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Empleado')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.CatalogoTipoExamen')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreRol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SignoVital',
            fields=[
                ('idSignoVital', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('presionArterial', models.CharField(max_length=10)),
                ('frecCardiaca', models.IntegerField()),
                ('frecRespiratoria', models.IntegerField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('fechaMedicion', models.DateField()),
                ('notas', models.TextField(max_length=50)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('idTurno', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fechaInicio', models.DateField()),
                ('horaInicio', models.DateTimeField()),
                ('fechaFin', models.DateField()),
                ('horaFin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('Empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expediente.Empleado')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('idContactoEmergencia', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('relacion', models.CharField(max_length=20)),
            ],
            bases=('expediente.persona',),
        ),
        migrations.AddField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Usuario'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expediente.Persona'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Paciente'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='signoVital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.SignoVital'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='especialidadEmpleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.EspecialidadEmpleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expediente.Persona'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expediente.Persona'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Empleado'),
        ),
        migrations.AddField(
            model_name='constanciamedica',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Consulta'),
        ),
        migrations.AddField(
            model_name='archivero',
            name='archivista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Empleado'),
        ),
        migrations.AddField(
            model_name='antecedentefamiliar',
            name='enfermedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.CatalogoEnfermedad'),
        ),
        migrations.AddField(
            model_name='antecedentefamiliar',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente'),
        ),
        migrations.AddField(
            model_name='contactoemergencia',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente'),
        ),
        migrations.AddField(
            model_name='contactoemergencia',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expediente.Persona'),
        ),
    ]
