# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='fechaConsulta',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='fechaProximaConsulta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogoalergia',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='catalogoenfermedad',
            name='descripcionEnfermedad',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='catalogomedicamento',
            name='efectosSecundarios',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='catalogomedicamento',
            name='modoUso',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='catalogotipoexamen',
            name='descripcionExamen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='observaciones',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='jVPM',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correoElectronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefonoFijo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefonoMovil',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tercerNombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='observacionesReceta',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referenciamedica',
            name='hallazgosMedicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referenciamedica',
            name='impresionDiagnostica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referenciamedica',
            name='motivoReferencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoexamen',
            name='descripcionResultado',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signovital',
            name='notas',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
