# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_remove_expediente_numeroarchivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoResultadoExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArchivo', models.TextField(max_length=20)),
                ('rutaArchivo', models.TextField(max_length=50)),
                ('descripcionArchivo', models.TextField(blank=True, max_length=50, null=True)),
                ('ResultadoExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.ResultadoExamen')),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(choices=[('Empleado Publico', 'Empleado Publico'), ('Empleado Privado', 'Empleado Privado'), ('Desempleado', 'Desempleado')], max_length=50),
        ),
    ]
