# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0003_auto_20171117_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoemergencia',
            name='relacion',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hijo', 'Hijo'), ('Hermano', 'Hermano'), ('Otro', 'Otro')], max_length=20),
        ),
    ]
