from django.contrib import admin
from apps.expediente.models import AntecedenteFamiliar, Archivero, CatalogoAlergia, CatalogoDepartamento, CatalogoEnfermedad, CatalogoMedicamento, CatalogoMunicipio, CatalogoTipoExamen, ConstanciaMedica, Consulta, Direccion, Empleado, CatalogoEspecialidadEmpleado, Expediente, IncapacidadMedica, OrdenExamenMedico, Paciente, Persona, RecetaMedica, RecetaMedicamento, ReferenciaMedica, ResultadoExamen, SignoVital, Turno, ContactoEmergencia

admin.site.register(AntecedenteFamiliar)
admin.site.register(Archivero)
admin.site.register(CatalogoAlergia)
admin.site.register(CatalogoDepartamento)
admin.site.register(CatalogoEnfermedad)
admin.site.register(CatalogoMedicamento)
admin.site.register(CatalogoMunicipio)
admin.site.register(CatalogoTipoExamen)
admin.site.register(ConstanciaMedica)
admin.site.register(Consulta)
admin.site.register(Direccion)
admin.site.register(Empleado)
admin.site.register(CatalogoEspecialidadEmpleado)
admin.site.register(Expediente)
admin.site.register(IncapacidadMedica)
admin.site.register(OrdenExamenMedico)
admin.site.register(Paciente)
admin.site.register(Persona)
admin.site.register(RecetaMedica)
admin.site.register(RecetaMedicamento)
admin.site.register(ReferenciaMedica)
admin.site.register(ResultadoExamen)
admin.site.register(SignoVital)
admin.site.register(Turno)
admin.site.register(ContactoEmergencia)
